#
#server:
#  port: 80
#
#nacos:
#  config:
#    server-addr: localhost:8848
#
#
#spring:
#  main:
#    allow-bean-definition-overriding: true
##
##  cloud:
##    nacos:
##      config:
##        import-check:
##          enabled: false
#  config:
#    import: optional:nacos:nacos-config.yaml
#
